### ISSUE TITLE
Build project : 'Display' does not contain a definition for 'GammaRamp' 

### ISSUE THREAD

**Issue by nuuxcode** [mcgrizzz/NVCP_Toggle#2]
Hi, im noob to C#, trying to rebuild project, so i can change the default value of "DefaultVibrance" to 100....

i get this error when trying to build:

![image](https://user-images.githubusercontent.com/24565896/153279968-f91873e2-c252-4bc1-b42f-115331750124.png)

`
Build started...
1>------ Build started: Project: NVCP Toggle, Configuration: Debug Any CPU ------
Restored C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\NVCP Toggle.csproj (in 13 ms).
1>C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\Program.cs(101,32,101,41): error CS1061: 'Display' does not contain a definition for 'GammaRamp' and no accessible extension method 'GammaRamp' accepting a first argument of type 'Display' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\Program.cs(101,48,101,64): error CS0246: The type or namespace name 'DisplayGammaRamp' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\Program.cs(110,32,110,41): error CS1061: 'Display' does not contain a definition for 'GammaRamp' and no accessible extension method 'GammaRamp' accepting a first argument of type 'Display' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\Program.cs(110,48,110,64): error CS0246: The type or namespace name 'DisplayGammaRamp' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\nuux\Downloads\NVCP_Toggle-master\Nvidia Settings Toggle\Program.cs(145,29,145,42): error CS1061: 'Display' does not contain a definition for 'DisplayScreen' and no accessible extension method 'DisplayScreen' accepting a first argument of type 'Display' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "NVCP Toggle.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

btw i did install NvAPIWrapper.Net  version : 0.8.1.101 and WindowsDisplayAPI version 1.3.0.13

any help for this noob pls, 

 thank your for this project <3

**Comment by mcgrizzz** [comment]
I had to build WindowsDisplayAPI myself from the repo. The latest release is not up to date hence the compilation error. Here's the repo: https://github.com/falahati/WindowsDisplayAPI

**Comment by nuuxcode** [comment]
Thanks a lot <3
