### ISSUE TITLE
Toggle doesn't work under default vibrance and hue

### ISSUE THREAD

**Issue by Zoxjib** [mcgrizzz/NVCP_Toggle#5]
https://github.com/mcgrizzz/NVCP_Toggle/blob/f3912779c467cce1e3221f393782f092915866f3/Nvidia%20Settings%20Toggle/Program.cs#L91

If the user uses this program only to adjust gamma, brightness and/or contrast but keeps the hue and vibrancy default then the If statement remains True and the toggle functionality doesn't work.

**Comment by mcgrizzz** [comment]
Fixed in latest release ([1.3.2](https://github.com/mcgrizzz/NVCP_Toggle/releases/tag/1.3.2)) through commit https://github.com/mcgrizzz/NVCP_Toggle/commit/566513787cf309f40b3dc5e037f7b982923223bd
